In [3]:
import numpy as np

In [45]:
np.random.seed(0)
a  = np.random.randint(0,10,[2,3])
a

array([[5, 0, 3],
       [3, 7, 9]])

# METHODES NDARRAY

### SUM()

In [24]:
a.prod() # produit de tous les elements du tableau

0

In [25]:
a.prod(axis=1) # la somme des elements pour chaque ligne


array([  0, 189])

In [11]:
a.sum(axis=0) # la somme des elements pour chaque colonne

array([ 8,  7, 12])

### cumsum()

In [13]:
a.cumsum() # permet de faire la somme cumulee de tous les elements du tbaleau

array([ 5,  5,  8, 11, 18, 27])

In [14]:
a.cumsum(axis=0) # somme cumulee dans par colonne

array([[ 5,  0,  3],
       [ 8,  7, 12]])

In [15]:
a.cumsum(axis=1) # somme cumulee par ligne

array([[ 5,  5,  8],
       [ 3, 10, 19]])

### sort  /  argsort

In [3]:
a.argsort()


array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [5]:
b = a.copy()
b.sort()
b

array([[0, 3, 5],
       [3, 7, 9]])

NP.UNIQUE(A, RETUN_COUNT=TRUE)

In [49]:
np.random.seed(0)
A = np.random.randint(1,9,(2,6))
A

array([[5, 8, 6, 1, 4, 4],
       [4, 8, 2, 4, 6, 3]])

In [50]:
values, counts = np.unique(A, return_counts=True)

print(values)
print(counts)

[1 2 3 4 5 6 8]
[1 1 1 4 1 2 2]


##### petite demo avec unique et argsort

In [51]:
values[counts.argsort()] # ce code permet de savoir que 1 se repete le
# le moin et 4 se repete le plus.

array([1, 2, 3, 5, 6, 8, 4])

# NAN CORRECTIONS

In [26]:
A = np.random.randn(5,5)
A[0, 2] = np.nan
A[4, 3] = np.nan

A

array([[-0.93576943, -0.26788808,         nan, -0.69166075, -0.39675353],
       [-0.6871727 , -0.84520564, -0.67124613, -0.0126646 , -1.11731035],
       [ 0.2344157 ,  1.65980218,  0.74204416, -0.19183555, -0.88762896],
       [-0.74715829,  1.6924546 ,  0.05080775, -0.63699565,  0.19091548],
       [ 2.10025514,  0.12015895,  0.61720311,         nan, -0.35224985]])

toutes les methodes statistiques vues ne fonctionnent que si 
nos donnees ne sont pas corrompues, c'est a dire qu'il n'y a pas de donnees manquantes ou que l'expression NAN N'est pas dans nous donees.
pour resoudre cela, on peut :
    1- utiliser des functions de calcule qui permet d'ignore ces valeurs manquantes (CES FONCTIONS COMMENCE PAR nan)
    2- remplacer ces valeurs innaproprye en valeur en passant par la methode isnan()

# 1

In [21]:
# 1- 

# la moyenne
np.nanmean(A)

-0.10083191272544835

In [22]:
# la varience

np.nanvar(A)

1.0854526714982564

In [23]:
# l'ecart_type

np.nanstd(A)

1.041850599413494

# 2

In [24]:
 # 2-
 
np.isnan(A) # return True pour tous la nan


array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

#### isnan() peut etre associer a d'autre fonctions

In [27]:
np.isnan(A).sum() # determine le nombre de nan disponible

2

In [28]:
np.isnan(A).sum() / A.size # determiner leurs pourcentages dans nos donnees

0.08

#### correction des nan

In [25]:
# on remplace tous le nan par 0
A[np.isnan(A)] = 0
A

array([[-0.52817175, -1.07296862,  0.        , -2.3015387 ,  1.74481176],
       [-0.7612069 ,  0.3190391 , -0.24937038,  1.46210794, -2.06014071],
       [-0.3224172 , -0.38405435,  1.13376944, -1.09989127, -0.17242821],
       [-0.87785842,  0.04221375,  0.58281521, -1.10061918,  1.14472371],
       [ 0.90159072,  0.50249434,  0.90085595,  0.        , -0.12289023]])

# ALGEBRE LINEAIRE

In [33]:
A = np.ones((2,3))
B = np.ones((3,2))

A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
# LA transpose de A .
            # on tuilise la l'attribut T

A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
# produits matricielle
        # ON UTILISE la mehtode dot()
        # remarque la le nombre de colonne de A EST EGALE AU nombre de line de B
        
print(A.dot(B))
print("//////////")
print(B.dot(A))

[[3. 3.]
 [3. 3.]]
//////////
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


D'une maniere generale quand on veux faire de l'algebre lineaire on a recours a un subpackage totalement dedier a ca (np.linalg)

In [52]:
A = np.random.randint(0,10,[3,3])
A

array([[4, 7, 6],
       [8, 8, 1],
       [6, 7, 7]])

In [53]:
# calcule du determinat 

np.linalg.det(A)

-105.99999999999997

In [54]:
# calcule de l'inverse de la matrice

np.linalg.inv(A)

array([[-0.46226415,  0.06603774,  0.38679245],
       [ 0.47169811,  0.0754717 , -0.41509434],
       [-0.0754717 , -0.13207547,  0.22641509]])

In [57]:
# determiner les valeurs propres et les vecteurs propres
        # souvent utiliser dans certains algorithmes(principal component analysis) pour faire de la 
        # reduction de dimension 
np.linalg.eig(A)

EigResult(eigenvalues=array([17.70132599, -1.88243915,  3.18111316]), eigenvectors=array([[ 0.55158127,  0.7784244 ,  0.29776565],
       [ 0.52191938, -0.626935  , -0.641113  ],
       [ 0.65065986, -0.03174819,  0.70732577]]))

EXERCIE :

standardiser la matrice A sur colonne

il existe plusieurs techniques.